### ISSUE TITLE
[fix]  Build Failure in FiniteDifferenceSolver Due to Eigen Matrix Explicit Constructor Initialization

### ISSUE THREAD

**Issue by DhruvJ22** [open-space-collective/open-space-toolkit-astrodynamics#334]
**Describe the bug**

The bug occurs in the FiniteDifferenceSolver.cpp file, specifically when attempting to initialize an Eigen::MatrixXd object with a brace-enclosed initializer list. This operation fails due to the explicit constructor of Eigen::Matrix, which does not allow implicit conversions that would be necessary for this kind of initialization. The error is triggered at the following line:

 `const MatrixXd coordinatesMatrix = {coordinates};`

This line attempts to copy-initialize an Eigen::MatrixXd object with a VectorXd (or similar), which is not directly supported due to the explicit nature of the Eigen::Matrix constructor. The error message provided by the compiler points out that the chosen constructor is explicit in copy-initialization, referencing the explicit constructor declaration in the Eigen library's Matrix.h file.

The issue stems from a misunderstanding or oversight regarding Eigen's initialization requirements, leading to a build failure when attempting to compile the FiniteDifferenceSolver.cpp source file.

**Steps to reproduce**
1. Fork and clone the repository. 
2. Start the dev environment in container: `make start-development`
```
cmake ..
make
```
Screenshot of the error message:
![Screenshot from 2024-02-06 00-38-08](https://github.com/open-space-collective/open-space-toolkit-astrodynamics/assets/33181026/0d86f492-4553-411f-8220-75fce293d542)

**Potential suggestion**

To resolve this issue, directly construct the MatrixXd object using a method that Eigen supports for converting or initializing from a VectorXd. If the intent is to create a matrix where coordinates are column elements then update to:
`const MatrixXd coordinatesMatrix = coordinates;`
If supposed to be a row in the matrix then:
`const MatrixXd coordinatesMatrix = coordinates.transpose();`

**Comment by vishwa2710** [comment]
Hi @DhruvJ22 . Thanks for making this ticket and the thorough write up. I'm surprised this is happening as the CI tests are passing and I cannot re-produce this locally. I even made a new fork and tried to build from scratch.
Quite confused how this is happening.
Can you share some details on your environment?
- What OS are you running this on?
- What version of docker are you using?
- Can you share the CMake settings that you used?

From within the docker shell can you try running:
- ostk-clean
- ostk-build

And see what you get?

**Comment by DhruvJ22** [comment]
Hi @vishwa2710, I hope the following details help: 

- OS: Ubuntu 20.04.6 LTS
- Docker: 24.0.7 build afdd53b
- CMake settings: [CMakeCache.txt](https://github.com/open-space-collective/open-space-toolkit-astrodynamics/files/14183769/CMakeCache.txt)

I keep running into the command not found error when I try the `otsk-clean` and `otsk-build`. It is possible that I missed a step in configuring the docker/setting up the project. This is a screenshot of the two commands in zsh and bash: 
![Screenshot from 2024-02-06 12-02-12](https://github.com/open-space-collective/open-space-toolkit-astrodynamics/assets/33181026/c24b0712-0e93-4543-ac9f-8e1136b2565e)
![Screenshot from 2024-02-06 12-01-57](https://github.com/open-space-collective/open-space-toolkit-astrodynamics/assets/33181026/fdbf3b76-113f-466d-bb0f-9f6ff49620f8)

I would appreciate any assistance in helping me realize if there is something that I missed to be able to run the two commands. Additionally, I will be happy to provide any further information that might help you. 
 
-

**Comment by vishwa2710** [comment]
Hi @DhruvJ22 , there's a small typo there, the commands are:
- **ostk-clean**
- **ostk-build**
I believe you are typing o**ts**k and not o**st**k
